# -*- coding: utf-8 -*-
"""Get_api_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aA4w1ObTGryZpHM6bT99urBipUlyilGv
"""

import json
import pandas as pd
import requests

data = requests.get("http://www.bom.gov.au/fwo/IDN60701/IDN60701.94598.json"
                  ).json()

headers= list(data['observations']['data'][0].keys())

df = pd.DataFrame(columns=headers)

for i in range(144):
  df.loc[i] = list(data['observations']['data'][i].values())

#df.head()
df.to_csv('data.csv')

print("Minimum Pressure: ",df['press'].min())
print("Mean Pressure: ",df['press'].mean())
print("Maximum Pressure: ",df['press'].max())