# -*- coding: utf-8 -*-
"""Scrapping_Soup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mM8fwWid2SiM8ZHZlAosCD_hDjJy3Dl-
"""

from bs4 import BeautifulSoup
import pandas as pd
import requests

URL = 'https://tim.blog/2017/11/18/booklist/'
page = requests.get(URL)
soup = BeautifulSoup(page.content, 'html.parser')
results = soup.find(id='main')

#print(results.prettify())
book_name = soup.find_all('i')
book_names = []
for book in book_name:
  book_names.append(book.get_text())

final_name = [s for s in book_names if len(s) > 3]
print(final_name)